##########
# SERVER #
##########

kind: pipeline
type: docker
name: Building

steps:
  - name: production
    image: plugins/docker
    settings:
      repo: registry.jonassjodin.com/portfolio-server
      registry: registry.jonassjodin.com
      target: production
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      context: ./server
      dockerfile: ./server/Dockerfile
      cache_from:
        - registry.jonassjodin.com/portfolio-server:prod-${DRONE_BRANCH}
        - registry.jonassjodin.com/portfolio-server:prod-${DRONE_COMMIT_BEFORE}
      tags:
        - prod-${DRONE_BRANCH}
        - prod-${CI_COMMIT_SHA}

  - name: integration
    image: plugins/docker
    settings:
      repo: registry.jonassjodin.com/portfolio-server
      registry: registry.jonassjodin.com
      target: integration
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      context: ./server
      dockerfile: ./server/Dockerfile
      cache_from:
        - registry.jonassjodin.com/portfolio-server:test-${DRONE_BRANCH}
        - registry.jonassjodin.com/portfolio-server:test-${DRONE_COMMIT_BEFORE}
      tags:
        - test-${DRONE_BRANCH}
        - test-${CI_COMMIT_SHA}
image_pull_secrets:
  - dockerconfigjson
---
kind: pipeline
type: docker
name: Testing

steps:
  - name: Testing
    image: registry.jonassjodin.com/portfolio-server:test-${CI_COMMIT_SHA}
    environment:
      HOST: server
    commands:
      - env
      - pwd
      - cd /app
      - until ping -c1 $HOST >/dev/null 2>&1; do echo "Attempting to connect..."; sleep 1; done
      - yarn jest --ci

services:
  - name: server
    image: registry.jonassjodin.com/portfolio-server:prod-${CI_COMMIT_SHA}
    environment:
      PORT: "80"
      EMAIL_HOST:
        from_secret: email_host
      EMAIL_PORT:
        from_secret: email_port
      EMAIL_USERNAME:
        from_secret: email_username
      EMAIL_PASSWORD:
        from_secret: email_password

depends_on:
  - Building
image_pull_secrets:
  - dockerconfigjson
---
kind: pipeline
type: docker
name: Pushing to prod

steps:
  - name: production
    image: plugins/docker
    settings:
      repo: registry.jonassjodin.com/portfolio-server
      registry: registry.jonassjodin.com
      target: production
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      context: ./server
      dockerfile: ./server/Dockerfile
      cache_from:
        - registry.jonassjodin.com/portfolio-server:prod-${CI_COMMIT_SHA}
      tags:
        - latest
        - 0.0.1
image_pull_secrets:
  - dockerconfigjson
          
trigger:
  branch:
    - master
depends_on:
  - Testing

##########
# CLIENT #
##########

